name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #-
      #  name: Build and push android
      #  uses: docker/build-push-action@v5
      #  with:
      #    push: true
      #    context: "{{defaultContext}}:6.7-android-aqt"
      #    tags: "${{ secrets.DOCKERHUB_USERNAME }}/qt6-android-aqt:latest"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:6.7-wasm-aqt"
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/qt6-wasm-aqt:latest"

  docker-ios:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:6.7-ios-aqt"
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/qt6-ios-aqt:latest"
\ No newline at end of file
